import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from 'next/script'
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Load MediaPipe FaceMesh via CDN */}
        <Script 
          src="https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh/face_mesh.js" 
          strategy="beforeInteractive" 
        />
        {/* The helper that handles the camera-to-model pipeline */}
        <Script 
          src="https://cdn.jsdelivr.net/npm/@mediapipe/camera_utils/camera_utils.js" 
          strategy="beforeInteractive" 
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
