import { create } from 'zustand';
import { throttle } from 'lodash';

/**
 * Interface representing the real-time biometric and focus state
 * generated by AttentionOS and consumed by FocusLens.
 */
interface AttentionState {
  // --- Core Metrics ---
  focusScore: number;         // 0-100 scale
  focusHistory: number[];    // New: Last 60 seconds of focus scores
  isFocused: boolean;        // Boolean threshold for UI interventions
  faceDetected: boolean;     // Whether the ML model sees a user

  // --- Biometric States ---
  isDrowsy: boolean;         // Derived from Blink Rate / EAR
  isDistracted: boolean;     // Derived from Gaze/Saccades
  headAligned: boolean;      // Derived from Yaw/Pitch/Roll

  // --- Session Analytics ---
  dwm: number;               // Deep Work Minutes (North Star Metric)
  sessionStartTime: number | null;
  lastTelemetrySync: number; // Timestamp of last backend POST

  // --- New Features: Heatmap & Audio Alerts ---
  gazeHeatmap: Array<{ x: number; y: number; weight: number; timestamp: number }>;
  alertHistory: Array<{ type: string; message: string; timestamp: number }>;
  isAudioMuted: boolean;
  isSpeechEnabled: boolean; // New: Text-to-Speech toggle
  alertSensitivity: 'low' | 'medium' | 'high';
  lastAlertTime: number;
  distractedSince: number | null; // New: Track when distraction started
  customAudioFiles: {
    low_focus?: string;
    fatigue?: string;
    distracted?: string;
    break_reminder?: string;
  };

  // --- Actions ---
  /**
   * Primary action to ingest data from the AttentionEngine loop.
   */
  updateFromEngine: (results: {
    focusScore: number;
    isDrowsy: boolean;
    isDistracted: boolean;
    headAligned: boolean;
    faceDetected: boolean;
    gazePosition?: { x: number; y: number };
  }) => void;

  /**
   * Add gaze point to heatmap
   */
  addGazePoint: (x: number, y: number) => void;

  /**
   * Trigger audio alert
   */
  triggerAlert: (type: 'low_focus' | 'fatigue' | 'distracted' | 'break_reminder', message: string) => void;

  /**
   * Toggle audio mute
   */
  toggleAudioMute: () => void;

  /**
   * Toggle speech alerts
   */
  toggleSpeech: () => void;

  /**
   * Update alert sensitivity
   */
  updateAlertSensitivity: (sensitivity: 'low' | 'medium' | 'high') => void;

  /**
   * Set custom audio file for alert type
   */
  setCustomAudioFile: (type: 'low_focus' | 'fatigue' | 'distracted' | 'break_reminder', audioUrl: string) => void;

  /**
   * Resets the current reading session.
   */
  resetSession: () => void;

  /**
   * Logic to increment Deep Work Minutes based on time spent in a FOCUSED state.
   */
  processDWM: () => void;
}

export const useFocusStore = create<AttentionState>((set, get) => ({
  // Initial State
  focusScore: 100,
  focusHistory: Array(60).fill(100),
  isFocused: true,
  faceDetected: false,
  isDrowsy: false,
  isDistracted: false,
  headAligned: true,
  dwm: 0,
  sessionStartTime: null,
  lastTelemetrySync: Date.now(),

  // New state for advanced features
  gazeHeatmap: [],
  alertHistory: [],
  isAudioMuted: false,
  isSpeechEnabled: true, // Enabled by default as requested
  alertSensitivity: 'medium',
  lastAlertTime: 0,
  distractedSince: null,
  customAudioFiles: {},

  updateFromEngine: throttle((results: {
    focusScore: number;
    isDrowsy: boolean;
    isDistracted: boolean;
    headAligned: boolean;
    faceDetected: boolean;
    gazePosition?: { x: number; y: number };
  }) => {
    const { focusScore, isDrowsy, isDistracted, headAligned, faceDetected, gazePosition } = results;

    set((state) => {
      // Add gaze point to heatmap if available
      if (gazePosition && faceDetected) {
        state.addGazePoint(gazePosition.x, gazePosition.y);
      }

      // Check for alert conditions
      const now = Date.now();
      const timeSinceLastAlert = now - state.lastAlertTime;
      const alertCooldown = 4000; // Increased cooldown to 4 seconds for better flow
      const SUSTAINED_DISTRACTION_LIMIT = 3000; // Must be distracted for 3 seconds to match reference

      // TTS Cancellation logic: stop speaking as soon as we regain focus
      const wasFocused = state.isFocused;
      const willBeFocused = focusScore > 60 && faceDetected && !isDrowsy && headAligned;

      if (!wasFocused && willBeFocused && typeof window !== 'undefined' && window.speechSynthesis) {
        window.speechSynthesis.cancel();
      }

      // Track how long the user has been distracted
      let currentDistractedSince = state.distractedSince;
      const isCurrentlyDistracted = !faceDetected || isDistracted || !headAligned || focusScore < 50;

      if (isCurrentlyDistracted) {
        if (!currentDistractedSince) {
          currentDistractedSince = now;
        }
      } else {
        currentDistractedSince = null;
      }

      // Trigger alerts only if distraction is SUSTAINED
      if (currentDistractedSince && (now - currentDistractedSince > SUSTAINED_DISTRACTION_LIMIT)) {
        if (timeSinceLastAlert > alertCooldown && (!state.isAudioMuted || state.isSpeechEnabled)) {
          const sensitivityThresholds = {
            low: { focus: 30, drowsy: true, distracted: true },
            medium: { focus: 50, drowsy: true, distracted: true },
            high: { focus: 60, drowsy: true, distracted: true }
          };

          const thresholds = sensitivityThresholds[state.alertSensitivity];

          if (focusScore < thresholds.focus) {
            state.triggerAlert('low_focus', 'Focus level is low. Please refocus on your work.');
          } else if (isDrowsy) {
            state.triggerAlert('fatigue', 'Signs of fatigue detected. Consider taking a break.');
          } else if (!headAligned) {
            state.triggerAlert('distracted', 'Attention drift detected. Please look back at the screen.');
          }
        }
      }

      const newHistory = [...state.focusHistory, Math.round(focusScore)].slice(-60);

      return {
        focusScore: Math.round(focusScore),
        focusHistory: newHistory,
        distractedSince: currentDistractedSince,
        // Threshold: Focus score > 60 is considered "Focused"
        isFocused: willBeFocused,
        isDrowsy,
        isDistracted,
        headAligned,
        faceDetected,
        // Initialize start time on first successful detection
        sessionStartTime: state.sessionStartTime || Date.now(),
      };
    });

    // Check if we should increment DWM (every minute)
    get().processDWM();
  }, 100), // Throttle to 100ms to prevent infinite loops

  addGazePoint: (x: number, y: number) => {
    set((state) => ({
      gazeHeatmap: [
        ...state.gazeHeatmap,
        { x, y, weight: 1, timestamp: Date.now() }
      ].slice(-500) // Keep last 500 gaze points for performance
    }));
  },

  triggerAlert: (type: 'low_focus' | 'fatigue' | 'distracted' | 'break_reminder', message: string) => {
    const now = Date.now();

    // Add to alert history
    set((state) => ({
      alertHistory: [
        ...state.alertHistory,
        { type, message, timestamp: now }
      ].slice(-50), // Keep last 50 alerts
      lastAlertTime: now
    }));

    // Play audio alert
    if (!get().isAudioMuted) {
      playAudioAlert(type);
    }

    // Play speech alert
    if (get().isSpeechEnabled) {
      speakAlert(message);
    }
  },

  toggleAudioMute: () => {
    set((state) => ({
      isAudioMuted: !state.isAudioMuted
    }));
  },

  toggleSpeech: () => {
    set((state) => ({
      isSpeechEnabled: !state.isSpeechEnabled
    }));
  },

  updateAlertSensitivity: (sensitivity: 'low' | 'medium' | 'high') => {
    set({ alertSensitivity: sensitivity });
  },

  setCustomAudioFile: (type: 'low_focus' | 'fatigue' | 'distracted' | 'break_reminder', audioUrl: string) => {
    set((state) => ({
      customAudioFiles: {
        ...state.customAudioFiles,
        [type]: audioUrl
      }
    }));
  },

  processDWM: () => {
    const { isFocused, sessionStartTime } = get();
    if (isFocused && sessionStartTime) {
      // Logic: Increment DWM in small fractional increments based on tracking loops
      // In a real app, you'd track the delta since last update.
      set((state) => ({
        dwm: state.dwm + (1 / 120), // Assuming 500ms loops, adds 1 min every 120 loops
      }));
    }
  },

  resetSession: () => set({
    dwm: 0,
    sessionStartTime: null,
    focusScore: 100,
    isFocused: true,
    gazeHeatmap: [],
    alertHistory: [],
    lastAlertTime: 0,
    distractedSince: null
  }),
}));

// Web Speech API Implementation
function speakAlert(message: string) {
  if (typeof window === 'undefined' || !window.speechSynthesis) return;

  // Cancel any ongoing speech to prevent overlapping
  window.speechSynthesis.cancel();

  const utterance = new SpeechSynthesisUtterance(message);
  utterance.rate = 1.0;
  utterance.pitch = 1.0;
  utterance.volume = 1.0;

  // Try to find a clear English voice
  const voices = window.speechSynthesis.getVoices();
  const englishVoice = voices.find(v => v.lang.startsWith('en')) || voices[0];
  if (englishVoice) utterance.voice = englishVoice;

  window.speechSynthesis.speak(utterance);
}

// Enhanced audio alert implementation with custom file support and faster response
function playAudioAlert(type: string) {
  try {
    const state = useFocusStore.getState();
    const customAudioUrl = state.customAudioFiles[type as keyof typeof state.customAudioFiles];

    // Use custom audio file if available
    if (customAudioUrl) {
      const audio = new Audio(customAudioUrl);
      audio.volume = 1.0; // Higher volume for better prominence
      audio.play().catch(error => {
        console.warn('Custom audio failed, falling back to synthetic:', error);
        playSyntheticAlert(type);
      });
      return;
    }

    // Fallback to synthetic sounds
    playSyntheticAlert(type);
  } catch (error) {
    console.warn('Audio alert failed:', error);
  }
}

// Synthetic alert sounds with faster response times
function playSyntheticAlert(type: string) {
  const audioContext = new (window.AudioContext || (window as any).webkitAudioContext)();

  // Create different sounds for different alert types with faster response
  const createAlertSound = (frequency: number, duration: number, type: OscillatorType = 'sine') => {
    const oscillator = audioContext.createOscillator();
    const gainNode = audioContext.createGain();

    oscillator.type = type;
    oscillator.frequency.setValueAtTime(frequency, audioContext.currentTime);
    oscillator.frequency.exponentialRampToValueAtTime(0.01, audioContext.currentTime + duration);

    gainNode.gain.setValueAtTime(1.0, audioContext.currentTime); // Max volume
    gainNode.gain.exponentialRampToValueAtTime(0.01, audioContext.currentTime + duration);

    oscillator.connect(gainNode);
    gainNode.connect(audioContext.destination);

    oscillator.start();
    oscillator.stop(audioContext.currentTime + duration);
  };

  switch (type) {
    case 'low_focus':
      // Faster, more urgent tone for low focus
      createAlertSound(440, 0.4, 'sine'); // Increased duration
      setTimeout(() => createAlertSound(554, 0.4, 'sine'), 400);
      break;
    case 'fatigue':
      // Softer, but longer tone
      createAlertSound(330, 0.8, 'triangle'); // Increased duration
      break;
    case 'distracted':
      // More urgent and continuous siren-like
      createAlertSound(880, 0.4, 'square');
      setTimeout(() => createAlertSound(660, 0.4, 'square'), 400);
      setTimeout(() => createAlertSound(880, 0.4, 'square'), 800);
      setTimeout(() => createAlertSound(660, 0.4, 'square'), 1200);
      break;
    case 'break_reminder':
      // Calm but concise
      createAlertSound(261, 1.0, 'sine');
      break;
  }
}
